[package]
name = "http-types-red-badger-temporary-fork"
version = "5.0.0"
authors = [
    "Yoshua Wuyts <yoshuawuyts@gmail.com>",
    "Red Badger <stuart.harris@red-badger.com>",
]
edition = "2018"
description = "Common types for HTTP operations."
documentation = "https://docs.rs/http-types"
readme = "README.md"
repository = "https://github.com/http-rs/http-types"
license = "MIT OR Apache-2.0"
keywords = ["h2", "http", "request", "response", "types"]
categories = [
    "asynchronous",
    "web-programming",
    "web-programming::http-client",
    "web-programming::http-server",
    "web-programming::websocket",
]

[package.metadata.docs.rs]
features = ["docs"]
rustdoc-args = ["--cfg", "feature=\"docs\""]

[dependencies]
anyhow = "1.0.100"
async-channel = "=1.9.0"
# features: async_std
async-std = { version = "1.13.2", optional = true }
base64 = "0.22.1"
# features: cookies
cookie = { version = "0.18.1", features = ["percent-encode"], optional = true }
facet = "0.30.0"
futures-lite = "2.6.1"
# features: hyperium/http
http = { version = "1.3.1", optional = true }
infer = "0.19.0"
pin-project-lite = "0.2.16"
rand = "0.9.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_qs = "0.15.0"
serde_urlencoded = "0.7.1"
url = { version = "2.5.7", features = ["serde"] }

[dev-dependencies]
async-std = { version = "1.13.2", features = ["attributes"] }
http = "1.3.1"

[features]
async_std = ["fs"]
cookie-secure = ["cookie/secure", "cookies"]
cookies = ["cookie"]
default = ["cookie-secure", "fs"]
docs = ["unstable"]
fs = ["async-std"]
hyperium_http = ["http"]
unstable = []

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ["cfg(backtrace)"] }
