[package]
name = "http-types-red-badger-temporary-fork"
version = "3.0.0"
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]
edition = "2018"
description = "Common types for HTTP operations."
documentation = "https://docs.rs/http-types"
readme = "README.md"
repository = "https://github.com/http-rs/http-types"
license = "MIT OR Apache-2.0"
keywords = ["h2", "http", "request", "response", "types"]
categories = [
  "asynchronous",
  "web-programming",
  "web-programming::http-client",
  "web-programming::http-server",
  "web-programming::websocket",
]

[package.metadata.docs.rs]
features = ["docs"]
rustdoc-args = ["--cfg", "feature=\"docs\""]

[dependencies]
anyhow = "1.0.26"
async-channel = "1.5.1"
# features: async_std
async-std = { version = "1.6.0", optional = true }
base64 = "0.13.0"
# features: cookies
cookie = { version = "0.14.0", features = ["percent-encode"], optional = true }
facet = "0.27.12"
futures-lite = "1.11.1"
# features: hyperium/http
http = { version = "0.2.0", optional = true }
infer = "0.2.3"
pin-project-lite = "0.2.0"
rand = "0.7.3"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
serde_qs = "0.8.3"
serde_urlencoded = "0.7.0"
url = { version = "2.1.1", features = ["serde"] }

[dev-dependencies]
async-std = { version = "1.6.0", features = ["attributes"] }
http = "0.2.0"

[features]
async_std = ["fs"]
cookie-secure = ["cookie/secure", "cookies"]
cookies = ["cookie"]
default = ["cookie-secure", "fs"]
docs = ["unstable"]
fs = ["async-std"]
hyperium_http = ["http"]
unstable = []

[lints.rust]
unexpected_cfgs = { level = "allow", check-cfg = ["cfg(backtrace)"] }
